version: '3.4'

services:

  db:
    container_name: 'todo_db'
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - todo-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: todolist

volumes:
  todo-data:
